"""Initial migration. mysql 4.

Revision ID: c6b2fd1e0983
Revises: 756f0f49087c
Create Date: 2024-02-13 00:09:24.325365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6b2fd1e0983'
down_revision = '756f0f49087c'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=4096),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.VARCHAR(length=4096),
               existing_nullable=True)

    # ### end Alembic commands ###
